### PR TITLE
fix(parser): resolve PHP require/include static targets to dependency edges (#1009)

### PR DESCRIPTION
**Pull request by alfhen**
## Summary

PHP's `require`/`require_once`/`include`/`include_once` produced no dependency edge at all — `PHPImportExtractor.importNodeTypes` only covered `use` declarations. Ruby (`require_relative`) and JavaScript (`require()`) both already resolve their equivalents; PHP was the odd one out (#1009).

`require`/`include` are **expressions**, not declarations, and can appear anywhere in a file (top-level, inside a function, inside a conditional) — most call sites (a variable, a bare constant, an arbitrary function call, an interpolated string) are only resolvable at runtime. Guessing at those would repeat the #928/#1008/#1056 fabrication shape this codebase has closed twice already this week. So this fix is deliberately narrow:

- **Resolves**: a plain string literal (`require 'includes/foo.php';`); `__DIR__`/`dirname(__FILE__)` concatenated with a literal (the file's own directory); and `dirname(__DIR__)` concatenated with a literal (its **parent** directory — added after real-corpus dogfooding on WordPress surfaced it as a common, equally sound idiom, see below). All three cases also handle the WordPress-style parenthesized form and match `__DIR__`/`__FILE__`/`dirname` case-insensitively (`__dir__`, `Dirname(__FILE__)`, etc. — confirmed empirically against a real PHP 8.4 interpreter that PHP's magic constants and built-in function names are both case-insensitive).
- **Skips** (returns nothing, never a bare unresolved specifier): a variable (`require $x;`), a bare constant (`require SOME_CONST . '/f.php';` — including WordPress's own `ABSPATH`, which is assigned dynamically at runtime, not a lexical constant), any function call other than `dirname()`, an interpolated string, and a bare OS-absolute literal (`require '/etc/passwd';`).
- **Existence-gated**: even a statically-resolved target is only emitted as an edge if `requireTargetExists` (`packages/parser/src/php-require.ts`) confirms the resolved path is a real **file** (not a directory — see Lien Review fix below) on disk before an edge is emitted at all — stronger than the existing PSR-4 resolution's single-candidate trust, because a require/include target is inferred from a string-concatenation heuristic, not a language-level guarantee.

## Implementation

- `packages/parser/src/ast/languages/php.ts` — new `PHPImportExtractor.extractStaticRequireTargets`, a full-file recursive scan (like the existing `extractReferencedFQCNs`, since require/include isn't confined to the top of the file) that returns `./`/`../`-prefixed specifiers for the statically-decidable shapes above. `dirLevelOf` handles the directory-climbing logic (`__DIR__`/`dirname(__FILE__)` = 0, `dirname(__DIR__)` = 1).
- `packages/parser/src/ast/extractors/types.ts` — new optional `LanguageImportExtractor.extractStaticRequireTargets` interface method (additive; only PHP implements it).
- `packages/parser/src/ast/symbols.ts` — new `appendStaticRequireTargets`, parallel to `appendReferencedFQCNs`, which resolves each raw specifier through the existing pipeline and drops it unless `requireTargetExists` confirms the target.
- `packages/parser/src/php-require.ts` — new, small, filesystem-touching module (mirrors `php-psr4.ts`/`js-directory-index.ts`'s pattern) exposing `requireTargetExists`.
- `packages/parser/src/ast/chunker.ts` — added `'php'` to `RESOLVE_RELATIVE_IMPORTS` (so `./`/`../`-prefixed require specifiers actually get resolved relative to the importing file — they weren't reached by this before, since PHP's `use` imports never need it), and `buildPhpManifestRoots` now threads `workspaceRoot` through **unconditionally** (previously only when `composer.json` declared a PSR-4 map) — otherwise a PHP project with no Composer manifest at all (the WordPress/legacy case this issue calls out as highest-value) would have no root for the new existence check to verify against. Zero behavior change for PSR-4 resolution itself (`resolvePsr4Import` already no-ops on an empty map).

## Real-corpus measurement (WordPress core)

Measured on **`WordPress/WordPress`** (shallow clone), the canonical require/include-heavy PHP codebase and precisely the `__DIR__`-based case this fix targets — not the synthetic fixture I originally reached for, per review feedback that a self-authored fixture is weak evidence:

| | files | edges | orphans |
|---|---|---|---|
| before (pre-fix, rebuilt from `HEAD^^`) | 2598 | **114** | 2560 (98.5%) |
| after (final, incl. both Lien Review fixes below) | 2598 | **336** | 2497 (96.1%) |

**114 → 336 edges, 98.5% → 96.1% orphan.** Isolated `LIEN_HOME` per measurement, never touching a shared index. Re-measured three times as fixes landed (initial fix, after the `isFile()` correction, after the case-insensitivity correction) — **336 all three times**. Neither correction changed the WordPress number: none of the 175 statically-resolved sites in this corpus happen to resolve to a directory, and WordPress core uses canonical-case magic constants/function names throughout (confirmed via grep — zero `__dir__`/`__file__`/`DIRNAME(`/`Dirname(` hits). Both fixes are still necessary in general (each proven by a dedicated unit test) and I'm reporting the unchanged number honestly rather than implying it moved.

**Resolve/skip breakdown**, via the actual parser (not grep, to avoid comment/prose false positives like `includeStacktraces`): 1901 PHP files scanned, 311 have at least one require/include site, **1456 total require/include AST sites**, **175 (12.0%) statically resolved**, **1281 (88.0%) honestly skipped**. The dominant skip reason (sampled directly) is WordPress's own `require_once ABSPATH . 'wp-admin/includes/admin.php';` idiom — `ABSPATH` is assigned dynamically in `wp-load.php`, not a lexical compile-time constant, so treating it as `__DIR__`-equivalent would be unsound. The `dirname(__DIR__)` case (added after finding it in `wp-admin/admin-ajax.php`, `admin-post.php`, `tools.php`, and 16 other files) is real, common, and just as lexically sound as `dirname(__FILE__)`.

**Fabrication check** (the #1056/#1008 shape: unrelated files returning identical dependent lists) — checked five target files, all distinct, all explicable:
- `wp-load.php`: 20 dependents (real bootstrap entry points: `wp-login.php`, `wp-cron.php`, `wp-admin/admin-ajax.php` via `dirname(__DIR__)`, etc.)
- `wp-admin/admin.php`: 68 dependents (nearly every `wp-admin/*.php` page script requires its sibling `admin.php` via `__DIR__`)
- `wp-blog-header.php`: 3 dependents
- `wp-admin/includes/admin.php` and `wp-includes/functions.php`: 0 dependents each (both referenced only via the unresolvable `ABSPATH`/constant form — correctly, honestly empty, not fabricated)

No two non-empty lists collide.

**Monolog** (232 files/2857 chunks, isolated `LIEN_HOME`): 405 edges/197 orphans both before and after — unchanged. Monolog's `src/`/`tests/` trees have exactly one real require/include site (`tests/bootstrap.php`'s `require __DIR__.'/../vendor/autoload.php';`), and its target is gitignored/external, not part of the indexed corpus. Confirmed the mechanism still fires on this exact file (its chunk gains `imports: ["vendor/autoload.php"]` when `vendor/` exists on disk). Monolog was simply the wrong corpus to demonstrate this fix on — a modern Composer library resolves nearly everything through PSR-4 instead.

## Lien Review findings (7 across 4 rounds, all valid, all fixed, zero false positives)

**Round 1:**
1. **🔴 `php-require.ts:33` — directory-fabrication bug.** `fs.existsSync` returns `true` for directories, so `require 'somedir'` where `somedir/` exists on disk would emit an edge to something PHP cannot actually require at runtime — the exact #928/#1008/#1056 shape this function's own doc comment says it exists to prevent. **Fixed**: switched to `fs.statSync(...).isFile()` wrapped in try/catch (statSync throws on a missing path). Added a regression test for the directory case — verified it fails against the old `existsSync` code (reproduces the exact bug) and passes with the fix.
2. **🟡 `extractors/types.ts:216` — doc drift.** The comment said "two" statically-resolvable shapes; a follow-up commit had added the third (`dirname(__DIR__)`) without updating it. **Fixed**: comment now says "three".
3. **🟡 `php-require.ts:5` — same root cause as #1.** Once `isFile()` was used, the "names a real file" wording became accurate. No further change needed (confirmed, not silently left broken).

**Round 2** (a fresh review pass on the round-1 fixes found two MORE instances of the exact same doc-drift claim, at sites my own sweep had missed):
4. **🟡 `php.ts:399` — same doc-drift claim as #2, different file.** Fixed: also updated to "three".
5. **🟡 `php.ts:525` (`dirLevelOf`) — case-sensitivity bug.** Compared `__DIR__`/`__FILE__`/`dirname` text case-sensitively, but PHP's magic constants and built-in function names are both case-insensitive at the language level — `__dir__`, `Dirname(__FILE__)`, `DIRNAME(__DIR__)` all behave identically to canonical casing. Verified empirically against a real PHP 8.4 interpreter (not just reasoning from the manual) before fixing. **Fixed**: lowercase the compared text before matching. Added a test pinning four non-canonical-case forms.

**Round 3** (a THIRD review pass caught a third instance of the same doc-drift claim, at a site my "sweep for it" in round 2 still missed — the claim was worded differently at each site, so a grep on the round-1 phrasing ("two"/"statically-decidable") didn't catch it):
6. **🟡 `chunker.ts:87` (`RESOLVE_RELATIVE_IMPORTS`) — same doc-drift claim, third site.** Fixed, this time by grepping for the CONCEPT (`dirname(__FILE__)|__DIR__`) rather than the phrasing, and reading every hit across `packages/parser/src/**/*.ts`. That sweep caught one more stale site the concept-grep also flagged (`php.test.ts`'s describe-block comment, which also wrongly said the method "only returns a `./`-prefixed specifier" — no longer true since `dirname(__DIR__)` produces `../`). Total sites found describing this shape list across the whole repo: **8** — 5 have been stale at some point across the three rounds (3 fixed in round 1/2, these 2 fixed here); the remaining 3 (the changeset, and `php.ts`'s own `resolveDirRelativeConcatenation`/`dirLevelOf` doc comments) were already accurate.

**Round 4** (a fourth review pass caught a genuine disagreement BETWEEN two sibling doc comments, not another instance of the same drift):
7. **🟡 `extractors/types.ts:226` — wrong adjective.** Said "a plain string literal"; `php.ts:400`'s own doc comment for the actual implementation correctly says "a plain, **non-absolute** string literal" (`resolveStaticRequireExpression` deliberately skips a literal starting with `/`). The interface doc was the imprecise one. **Fixed**: one-word change to match.

This repo's dominant defect generator is one decision implemented at N sites, fixed at fewer than N (see #934) — this PR reproduced that pattern on its own documentation across four straight rounds, which is itself worth recording: a deliberate sweep for a known pattern, done twice, still undercounted the sites because each one worded the claim differently, and a genuinely NEW instance (the missing adjective) surfaced only once the drift-hunting stopped finding drift. Zero false positives across all 7 findings, including a real fabrication hole (`existsSync` on directories) and a case-insensitivity gap verified against a live PHP interpreter — Lien Review did real work on its own PR.

## Test that fails on pre-fix code

`packages/parser/src/ast/chunker.test.ts`'s `PHP require/include static-target resolution (#1009)` describe block. Verified by reverting `chunker.ts`/`extractors/types.ts`/`php.ts`/`symbols.ts` to the pre-fix commit and deleting `php-require.ts`, then re-running — the positive resolution tests fail (`TypeError: importExtractor.extractStaticRequireTargets is not a function` / missing edges), confirming they weren't decoys. Restored the fix afterward and re-ran the full suite green. Separately, `php-require.test.ts`'s new directory-case test was verified against the pre-`isFile()` code (fails, as expected) before the fix landed.

## Regressions

Full `packages/parser` suite (1782 tests, all pass), full `npm test` across the monorepo (27+1782+407+1748+1637+41 tests, all pass), `npm run test:e2e:php -w packages/cli` (18 passed, including the #1004 collapse-to-zero detector on Monolog). The change is additive and PHP-scoped: the new interface method is optional (7 other language extractors untouched), `RESOLVE_RELATIVE_IMPORTS`/`buildPhpManifestRoots` changes only affect PHP's own resolution path.

## `expectedMinDependencyEdges` floor

Not tightened. Monolog's floor (`packages/cli/test/e2e/real-projects.test.ts`, currently `20`) doesn't move because of this fix (measured unchanged, see above) — tightening it anyway would be scope creep onto #1053's separate, already-open concern about these floors sitting far below measured across the board. For the record: the e2e test's own 100-file sampled sweep of Monolog measures ~39 edges against the floor of 20, so today it would only catch roughly a 49%+ collapse in that sample.

## Gates

- `npm run format:check` — pass
- `npm run lint` — 0 errors (41 pre-existing warnings, none in touched files)
- `npm run typecheck` — pass
- `npm run build` — pass
- `npm test` — pass (27+1782+407+1748+1637+41 tests)
- `npm run test:e2e:php -w packages/cli` — pass (18 tests)
- `lien delta --base origin/main` — exit 0 (new functions max cognitive complexity 9, well under threshold)

Rebased three times onto `origin/main` (through #1061, #1064, and #1065) to pick up concurrent PRs merging while this one was in flight — including #1065's own fix for #1056 (Rust bare crate-root imports), one of the fabrication precedents cited throughout this PR's own review. Re-measured WordPress post-rebase each time to confirm no regression; 336 edges held steady across all three post-review-fix re-measurements (initial fix, `isFile()` fix, case-insensitivity fix).

---

### Lien Review

✅ **Good** - No complexity issues found.

> [!WARNING]
> **1 issue found** · Low Risk
>
> This PR adds PHP static require/include dependency extraction by threading `workspaceRoot` through `ManifestRoots`, resolving `dirname(__FILE__)`/`__DIR__`-based paths, and confirming target files exist on disk before emitting edges. The implementation is generally sound, but the `buildManifestRoots` documentation was not updated to reflect that PHP now always returns a roots object even when no manifest-declared roots are found.
>
> - Added PHP AST-based extraction of static require/include targets with `__DIR__`/`dirname(__FILE__)` normalization
> - Threaded `workspaceRoot` through `ManifestRoots` so PHP require/include targets can be verified against the filesystem
> - Added PSR-4 manifest root building for PHP projects

✅ *Trust: **Delivered** — The review ran to completion within budget.*

**Findings (1)**

- 🟡 **bug** in `buildManifestRoots` — `packages/parser/src/ast/chunker.ts:193`
  The JSDoc on `buildManifestRoots` claims the function returns `undefined` "when nothing is found", but the new PHP builder always returns a `ManifestRoots` object (with an empty `psr4Map`) whenever `workspaceRoot` is provided, even if no `composer.json` or PSR-4 mapping exists. This contradicts the documented contract and misleads callers about when resolution steps are skipped.
  💡 *Update the `buildManifestRoots` doc comment to note that PHP unconditionally returns a roots object (using `workspaceRoot` for require/include existence checks), while other languages may still return `undefined` when no manifest is present.*

<sup>Reviewed by [Lien Review](https://lien.dev) for commit cbcf6fc. Updates automatically on new commits.</sup>

### CODE REVIEW

File: packages/parser/src/php-require.ts [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+ * @param specifier - The already relative-resolved (workspace-relative)
+ *   candidate path, as produced by `resolveImportSpecifier`.
+ * @param workspaceRoot - Absolute project root. Returns `false` when absent
+ *   (nothing to check against) — callers with no workspace root in scope
+ *   (most unit tests, and any indexing run that never provided one)
+ *   correctly see zero require/include edges rather than an unverified guess.
+ */
+export function requireTargetExists(specifier: string, workspaceRoot: string | undefined): boolean {
+  if (!workspaceRoot) return false;
+  return fs.existsSync(path.join(workspaceRoot, specifier));
```
[the remark this answers is not in the document]
Comment (alfhen) [reply packages/parser/src/php-require.ts]: Fixed: switched `requireTargetExists` from `fs.existsSync` to `fs.statSync(...).isFile()` (wrapped in try/catch, since `statSync` throws on a missing path). Added a regression test for the directory case in `php-require.test.ts` — verified it fails against the old `existsSync` code and passes with the fix. See commit d460805d.

File: packages/parser/src/ast/extractors/types.ts [hunk 2]
```diff
@@ -211,6 +211,43 @@ export interface LanguageImportExtractor {
    *   manifest-root resolution).
    */
   extractReferencedFQCNs?(rootNode: SyntaxNode): string[];
+
+  /**
+   * Extract `require`/`require_once`/`include`/`include_once` targets that
```
[the remark this answers is not in the document]
Comment (alfhen) [reply packages/parser/src/ast/extractors/types.ts:225]: Fixed: extractors/types.ts now says three statically-decidable shapes (added dirname(__DIR__) to the list). Also swept the repo for the same stale claim per feedback and found two more instances I'd missed in php.ts itself (extractStaticRequireTargets and resolveStaticRequireExpression's own doc comments) -- all three now corrected in commit db60fac8.

File: packages/parser/src/php-require.ts [hunk 3]
```diff
@@ -0,0 +1,34 @@
+import fs from 'fs';
+import path from 'path';
+
+/**
+ * Verifies a `PHPImportExtractor.extractStaticRequireTargets` result actually
```
[the remark this answers is not in the document]
Comment (alfhen) [reply packages/parser/src/php-require.ts:5]: Resolved by the isFile() fix (see reply on the sibling finding above): the doc comment's 'names a real file' wording is now accurate, since the implementation actually verifies that (directories are correctly rejected). No further change needed.

File: packages/parser/src/ast/languages/php.ts [hunk 4]
```diff
@@ -364,6 +364,196 @@ export class PHPImportExtractor implements LanguageImportExtractor {
...
+   * interpolation, by checking its children, not its node type.
+   */
+  private static readonly STRING_LITERAL_NODE_TYPES = new Set(['string', 'encapsed_string']);
+
+  /**
+   * Scan the WHOLE file (recursively, like `extractReferencedFQCNs`) for
+   * `require`/`include` targets that are statically resolvable to a concrete
+   * path relative to this file's own directory. See
+   * `LanguageImportExtractor.extractStaticRequireTargets`'s doc comment for
+   * the full contract; only two shapes are accepted here:
```
[the remark this answers is not in the document]
Comment (alfhen) [reply packages/parser/src/ast/languages/php.ts]: Fixed, same as the sibling finding on extractors/types.ts: this doc comment now lists dirname(__DIR__) as the third accepted shape. Found via a repo-wide grep sweep for the stale claim (per feedback) rather than fixing only the flagged instance -- three sites total, all corrected in commit db60fac8.

File: packages/parser/src/ast/languages/php.ts [hunk 5]
```diff
@@ -364,6 +364,196 @@ export class PHPImportExtractor implements LanguageImportExtractor {
...
+   *
+   * Deliberately does not recurse into further nesting
+   * (`dirname(dirname(__FILE__))`) or PHP 8's two-argument `dirname($path,
+   * $levels)` form -- both real but rare (a handful of sites total on the
+   * same corpus that motivated the `dirname(__DIR__)` case, confined to a
+   * single vendored library) -- left as an honest, documented remainder
+   * rather than added speculatively.
+   */
+  private dirLevelOf(node: SyntaxNode): number | null {
+    if (node.type === 'name' && node.text === '__DIR__') return 0;
```
[the remark this answers is not in the document]
Comment (alfhen) [reply packages/parser/src/ast/languages/php.ts]: Confirmed and fixed: verified empirically against a real PHP 8.4 interpreter that __dir__/__file__ and dirname()/DIRNAME()/Dirname() all behave identically to their canonical-case spelling. dirLevelOf now lowercases the compared text before matching __dir__/__file__/dirname. Added a test pinning four non-canonical-case forms (__dir__, dirname(__file__), Dirname(__FILE__), DIRNAME(__DIR__)) in commit db60fac8.

File: packages/parser/src/ast/chunker.ts [hunk 6]
```diff
@@ -83,11 +83,22 @@ function parseAndValidate(filepath: string, content: string) {
  * relationship (Python's dot-counting maps directly onto ascending
  * directories from the importer's own), so it's safe to resolve here the
  * same way JS/TS specifiers are.
+ *
+ * Includes PHP (#1009): `PHPImportExtractor.extractStaticRequireTargets`
```
[the remark this answers is not in the document]
Comment (alfhen) [reply packages/parser/src/ast/chunker.ts:87]: Fixed, and this time by grepping for the CONCEPT (dirname(__FILE__)|__DIR__ across packages/parser/src/**/*.ts) rather than the phrasing, per feedback -- the previous sweep matched on 'two'/'statically-decidable' and missed this site plus one more (php.test.ts's describe-block comment, which also incorrectly said this method 'only returns a ./-prefixed specifier' -- no longer true since dirname(__DIR__) produces ../). Both fixed in commit 21160fd5. Total sites found describing this shape list across the whole repo: 8 -- 5 have been stale at some point across the two rounds (3 fixed previously, these 2 now), the remaining 3 (the changeset, and php.ts's own resolveDirRelativeConcatenation/dirLevelOf doc comments) were already accurate.

File: packages/parser/src/ast/languages/php.ts [hunk 7]
```diff
@@ -364,6 +364,210 @@ export class PHPImportExtractor implements LanguageImportExtractor {
...
+   * finding): PHP's magic constants and its built-in function names are both
+   * case-insensitive at the language level -- `__dir__`, `__Dir__`, and
+   * `Dirname(__FILE__)` all behave identically to their canonical-case
+   * spelling. A case-sensitive comparison would silently under-resolve any
+   * legacy PHP file using non-canonical casing, which is exactly the kind of
+   * codebase this fix targets -- a MISS, not a fabrication risk, since it
+   * only means falling through to `null` (skip) rather than producing a
+   * wrong answer.
+   */
+  private dirLevelOf(node: SyntaxNode): number | null {
```
[the remark this answers is not in the document]
Comment (alfhen) [reply packages/parser/src/ast/languages/php.ts:546]: Confirmed and fixed: dirLevelOf now requires args.namedChildren.length === 1 before matching __FILE__/__DIR__ at all -- the two-argument dirname($path, $levels) form falls through to null (the documented unsupported remainder) instead of being misresolved. Added tests for dirname(__FILE__, 2) and dirname(__DIR__, 2) asserting no edge is emitted -- verified both fail without the guard (reproduce the exact fabrication described) and pass with it. Re-measured WordPress after this fix: still 336 edges (unchanged) -- none of that corpus's own dirname($path, 2) sites happened to misresolve to a path that coincidentally exists on disk, so the bug was real but not yet observed to fire there; the fix closes it regardless.

File: packages/parser/src/ast/extractors/types.ts [hunk 8]
```diff
@@ -220,6 +220,43 @@ export interface LanguageImportExtractor {
...
+   * are STATICALLY resolvable to a concrete file: a plain string literal, or
```
[the remark this answers is not in the document]
Comment (alfhen) [reply packages/parser/src/ast/extractors/types.ts]: Fixed: extractors/types.ts now says 'a plain, non-absolute string literal', matching php.ts:400's wording exactly.

File: packages/parser/src/php-require.ts [hunk 9]
```diff
@@ -0,0 +1,38 @@
...
+ *   correctly see zero require/include edges rather than an unverified guess.
+ */
+export function requireTargetExists(specifier: string, workspaceRoot: string | undefined): boolean {
+  if (!workspaceRoot) return false;
+  try {
+    return fs.statSync(path.join(workspaceRoot, specifier)).isFile();
+  } catch {
+    return false;
+  }
+}
```
[the remark this answers is not in the document]
Comment (alfhen) [reply packages/parser/src/php-require.ts:38]: Valid, and being fixed in a small follow-up PR rather than a seventh round on this one — but the stated impact is overstated and worth correcting for the record.

`path.join` does resolve `..` without clamping, so `requireTargetExists` can `statSync` a path outside `workspaceRoot`. Agreed, and a boundary check belongs here — this function exists to be a guard, so an unguarded escape is out of character for it.

But it does **not** "add `workspace/…` as a trusted import edge". The escaped specifier (e.g. `../../../etc/passwd`) is recorded in the chunk's `imports` metadata, and `matchesFile` then has to match it against an **indexed** file to produce a dependent edge. Nothing outside the workspace is indexed, so no edge ever materialises. The real cost is a junk metadata entry plus one wasted `stat` outside the project — not a fabricated dependency, which is the failure mode that would have justified blocking the merge (cf. the `existsSync`/directory finding earlier on this PR, which genuinely could fabricate an edge and did block it).

Landing #1063 now: Lien Review returned clean on `cbcf6fc`, all 22 checks pass, and the two sibling doc findings in this batch are already fixed on the current head. The boundary check follows immediately as a standalone 2-line PR.
